/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package program_siswa;
//LIBRARY
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import com.mysql.cj.jdbc.Driver;
import com.mysql.jdbc.*;
/**
 *
 * @author USER
 */
public class guru extends javax.swing.JFrame {

    /**
     * Creates new form guru
     */
    public guru() {
        initComponents();
        tglskrg();
        this.setSize(600,700);
        tabel1.setModel(tblModel);
        Tabel(tabel1, new int[]{120,180,120,120});
        setDefaultTable();
    }
    
    //MENAMPILKAN TANGGAL
    public void tglskrg(){
    Date skrg= new Date();
    SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
    String tgl = format.format(skrg);
    txttgl.setText(format.format(skrg));
    }
    
    //KONEKSI KE DATABASE
    public void setDefaultTable() {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try {
    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
    //memanggil variable hubung
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    String SQL = "Select * from guru";
    //res = variable
    ResultSet res = stt.executeQuery(SQL);
    while(res.next()) {
        //digunakan untuk mengisi data tabel
    data[0] = res.getString(1);
    data[1] = res.getString(2);
    data[2] = res.getString(3);
    data[3] = res.getString(4);
    data[4] = res.getString(5);
    tblModel.addRow(data);
    }
    res.close();
    stt.close();
    kon.close();
    } catch(Exception exc) {
    System.err.println(exc.getMessage());
    }
    }
    
    //MEMBUAT PENGATURAN TABEL
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    private void Tabel(javax.swing.JTable tb, int lebar[]) {
    tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    int kolom=tb.getColumnCount();
    for(int i=0;i < kolom;i++) {
    javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
    tbc.setPreferredWidth(lebar[i]);
    tb.setRowHeight(17);
    }
    }
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
    return new javax.swing.table.DefaultTableModel(
    new Object [][]{},
    //digunakan untuk menampilkan judul table
    new String []{"NIS","NAMA","MAPEL","JENIS KELAMIN","STATUS"}
    ){
    boolean[] canEdit = new boolean []{
    false, false, false, false
    };
    public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
    }
    };
    }

    int row = 0;
    public void Tampil(){
    row = tabel.getSelectedRow();
    txtnis.setText(tblModel.getValueAt(row,0).toString());
    txtnama.setText(tblModel.getValueAt(row,1).toString());
    txtmapel.setText(tblModel.getValueAt(row,2).toString());
    if(tblModel.getValueAt(row, 3).toString().equals("Laki-Laki")){
    rdlaki.setSelected(true);
    }else{
    rdperempuan.setSelected(true);
    }
    
    if(tblModel.getValueAt(row, 3).toString().equals("Aktif")){
    rdaktif.setSelected(true);
    }else{
    rdnonaktif.setSelected(true);
    }
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        cmdsimpan = new javax.swing.JButton();
        cmdubah = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        cmdkeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmapel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdlaki = new javax.swing.JCheckBox();
        rdperempuan = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        rdaktif = new javax.swing.JCheckBox();
        rdnonaktif = new javax.swing.JCheckBox();
        Panel1 = new javax.swing.JPanel();
        cmdsimpan1 = new javax.swing.JButton();
        cmdubah1 = new javax.swing.JButton();
        cmdhapus1 = new javax.swing.JButton();
        cmdkeluar1 = new javax.swing.JButton();
        txttgl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray), "Tombol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 11))); // NOI18N

        cmdsimpan.setBackground(new java.awt.Color(51, 255, 0));
        cmdsimpan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdsimpan.setForeground(new java.awt.Color(255, 255, 255));
        cmdsimpan.setText("Simpan");
        cmdsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmdsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpanActionPerformed(evt);
            }
        });

        cmdubah.setBackground(new java.awt.Color(255, 255, 0));
        cmdubah.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdubah.setText("Ubah");
        cmdubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubahActionPerformed(evt);
            }
        });

        cmdhapus.setBackground(new java.awt.Color(255, 0, 0));
        cmdhapus.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdhapus.setForeground(new java.awt.Color(255, 255, 255));
        cmdhapus.setText("Hapus");
        cmdhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapusActionPerformed(evt);
            }
        });

        cmdkeluar.setBackground(new java.awt.Color(255, 0, 0));
        cmdkeluar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdkeluar.setForeground(new java.awt.Color(255, 255, 255));
        cmdkeluar.setText("Keluar");
        cmdkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cmdsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabel.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NIS", "NAMA", "JENIS KELAMIN", "JURUSAN"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA GURU");

        jLabel2.setText("NIS");

        jLabel3.setText("NAMA");

        jLabel4.setText("MAPEL");

        jLabel5.setText("JENIS KELAMIN");

        rdlaki.setText("Laki-Laki");

        rdperempuan.setText("Perempuan");

        jLabel6.setText("STATUS GURU");

        rdaktif.setText("Aktif");

        rdnonaktif.setText("Tidak Aktif");

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.gray), "Tombol", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 1, 11))); // NOI18N

        cmdsimpan1.setBackground(new java.awt.Color(51, 255, 0));
        cmdsimpan1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdsimpan1.setForeground(new java.awt.Color(255, 255, 255));
        cmdsimpan1.setText("Simpan");
        cmdsimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmdsimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdsimpan1ActionPerformed(evt);
            }
        });

        cmdubah1.setBackground(new java.awt.Color(255, 255, 0));
        cmdubah1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdubah1.setText("Ubah");
        cmdubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdubah1ActionPerformed(evt);
            }
        });

        cmdhapus1.setBackground(new java.awt.Color(255, 0, 0));
        cmdhapus1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdhapus1.setForeground(new java.awt.Color(255, 255, 255));
        cmdhapus1.setText("Hapus");
        cmdhapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdhapus1ActionPerformed(evt);
            }
        });

        cmdkeluar1.setBackground(new java.awt.Color(255, 0, 0));
        cmdkeluar1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        cmdkeluar1.setForeground(new java.awt.Color(255, 255, 255));
        cmdkeluar1.setText("Keluar");
        cmdkeluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdkeluar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(cmdsimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdubah1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdhapus1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cmdkeluar1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdubah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdhapus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdkeluar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txttgl.setText("22 September 2005");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Date:");

        tabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabel1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIS", "NAMA", "MAPEL", "JENIS KELAMIN", "STATUS GURU"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdlaki)
                                            .addComponent(rdaktif))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdnonaktif)
                                            .addComponent(rdperempuan)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel1)))
                .addContainerGap(161, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttgl)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttgl)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdlaki)
                            .addComponent(rdperempuan)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdaktif)
                        .addComponent(jLabel6))
                    .addComponent(rdnonaktif))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String data[]=new String[4];
    
    private void cmdsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpanActionPerformed
        // TODO add your handling code here:
        //JENIS KELAMIN
        String jenkel="";
        if(rdlaki.isSelected())
        jenkel="Laki-Laki";
        else
        jenkel="Perempuan";
        
        //STATUS GURU
        String status_guru="";
        if(rdaktif.isSelected())
        status_guru="Aktif";
        else
        status_guru="Tidak Aktif";
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "insert into guru values('"+txtnis.getText()+"','"+txtnama.getText()+"','"+txtmapel.getText()+"','"+jenkel+"','"+status_guru+"')";
            stt.executeUpdate(SQL);
            data[0]=txtnis.getText();
            data[1]=txtnama.getText();
            data[2]=txtmapel.getText();
            data[3]=jenkel;
            data[4]=status_guru;
            tblModel.insertRow(0, data);
            txtnis.setText("");
            txtnama.setText("");
            txtmapel.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_cmdsimpanActionPerformed

    private void cmdubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubahActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            //JENIS KELAMIN
            String jenkel="";
            if(rdlaki.isSelected())
            jenkel="Laki-Laki";
            else
            jenkel="Perempuan";

            //STATUS GURU
            String status_guru="";
            if(rdaktif.isSelected())
            status_guru="Aktif";
            else
            status_guru="Tidak Aktif";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "update guru set nama='"+txtnama.getText()+"','"+txtmapel.getText()+"',"+"jenkel='"+jenkel+","+"status_guru='"+status_guru+"'where nis='"+txtnis.getText()+"'";
            stt.executeUpdate(SQL);
            data[0]=txtnis.getText();
            data[1]=txtnama.getText();
            data[2]=txtmapel.getText();
            data[3]=jenkel;
            data[4]=status_guru;
            tblModel.removeRow(row);
            tblModel.insertRow(row, data);
            txtnis.setText("");
            txtnama.setText("");
            txtmapel.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_cmdubahActionPerformed

    private void cmdhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapusActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "delete from guru where nis='"+txtnis.getText()+"'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
            txtnis.setText("");
            txtnama.setText("");
            txtmapel.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_cmdhapusActionPerformed

    private void cmdkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdkeluarActionPerformed

    private void cmdsimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdsimpan1ActionPerformed
        // TODO add your handling code here:
        //JENIS KELAMIN
        String jenkel="";
        if(rdlaki.isSelected())
        jenkel="Laki-Laki";
        else
        jenkel="Perempuan";
        
        //STATUS GURU
        String status_guru="";
        if(rdaktif.isSelected())
        status_guru="Aktif";
        else
        status_guru="Tidak Aktif";
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "insert into guru values('"+txtnis.getText()+"','"+txtnama.getText()+"','"+txtmapel.getText()+"','"+jenkel+"','"+status_guru+"')";
            stt.executeUpdate(SQL);
            data[0]=txtnis.getText();
            data[1]=txtnama.getText();
            data[2]=txtmapel.getText();
            data[3]=jenkel;
            data[4]=status_guru;
            tblModel.insertRow(0, data);
            txtnis.setText("");
            txtnama.setText("");
            txtmapel.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_cmdsimpan1ActionPerformed

    private void cmdubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdubah1ActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            //JENIS KELAMIN
            String jenkel="";
            if(rdlaki.isSelected())
            jenkel="Laki-Laki";
            else
            jenkel="Perempuan";

            //STATUS GURU
            String status_guru="";
            if(rdaktif.isSelected())
            status_guru="Aktif";
            else
            status_guru="Tidak Aktif";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "update guru set nama='"+txtnama.getText()+"','"+txtmapel.getText()+"',"+"jenkel='"+jenkel+","+"status_guru='"+status_guru+"'where nis='"+txtnis.getText()+"'";
            stt.executeUpdate(SQL);
            data[0]=txtnis.getText();
            data[1]=txtnama.getText();
            data[2]=txtmapel.getText();
            data[3]=jenkel;
            data[4]=status_guru;
            tblModel.removeRow(row);
            tblModel.insertRow(row, data);
            txtnis.setText("");
            txtnama.setText("");
            txtmapel.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_cmdubah1ActionPerformed

    private void cmdhapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdhapus1ActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "delete from guru where nis='"+txtnis.getText()+"'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
            txtnis.setText("");
            txtnama.setText("");
            txtmapel.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_cmdhapus1ActionPerformed

    private void cmdkeluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdkeluar1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmdkeluar1ActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // Digunakan untuk menampilkan data yang sudah ada pada table dgn klik 2x mouse
        if(evt.getClickCount()==2){
            Tampil();
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // Digunakan untuk menampilkan data yang sudah ada pada table dgn klik 2x mouse
        if(evt.getClickCount()==2){
            Tampil();
        }
    }//GEN-LAST:event_tabel1MouseClicked

    //MEMBUAT FRAME DI TENGAH
    public guru(JFrame form) {
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (dim.width-form.getSize().width)/2;
    int y = (dim.height-form.getSize().height)/2;
    form.setLocation(x,y);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdhapus1;
    private javax.swing.JButton cmdkeluar;
    private javax.swing.JButton cmdkeluar1;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JButton cmdsimpan1;
    private javax.swing.JButton cmdubah;
    private javax.swing.JButton cmdubah1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox rdaktif;
    private javax.swing.JCheckBox rdlaki;
    private javax.swing.JCheckBox rdnonaktif;
    private javax.swing.JCheckBox rdperempuan;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField txtmapel;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnis;
    private javax.swing.JLabel txttgl;
    // End of variables declaration//GEN-END:variables
}
