/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gunawan Widya Nugraha
 */
 
package program_siswa;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement; 
import java.sql.*;
import com.mysql.cj.jdbc.Driver;
import com.mysql.jdbc.*;
import javax.swing.*;
 
public class nilai extends javax.swing.JFrame {

    /**
     * Creates new form nilai
     */
    public nilai() {
        initComponents();
        tampil_nis();
        tampil_nip();
    }

    String data[]=new String[9];
    //KONEKSI KE DATABASE
    public void setDefaultTable() {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try {
    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
    //memanggil variable hubung
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    String SQL = "Select * from nilai";
    //res = variable
    ResultSet res = stt.executeQuery(SQL);
    while(res.next()) {
    //digunakan untuk mengisi data tabel
    data[0] = res.getString(1);
    data[1] = res.getString(2);
    data[2] = res.getString(3);
    data[3] = res.getString(4);
    data[4] = res.getString(5);
    data[5] = res.getString(6);
    data[6] = res.getString(7);
    data[7] = res.getString(8);
    data[8] = res.getString(9);
    }
    res.close();
    stt.close();
    kon.close();
    } catch(Exception exc) {
    System.err.println(exc.getMessage());
    }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int row = 0;
    public void Tampil(){
    //tnis.setSelectedItem(tblModel.getValueAt(row,3).toString());
    }
    
    @SuppressWarnings("unchecked")
        public void tampil_nis(){
        String hubung="jdbc:mysql://localhost:3306/sekolah";
        try{
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        Connection con=DriverManager.getConnection(hubung,"root","");
        Statement stt=con.createStatement();
        String sql = "Select NIS from siswa order by NIS asc";
        ResultSet res= stt.executeQuery(sql);
        while(res.next()){
        Object[] ob = new Object[1];
        ob[0] = res.getString(1);
        tnis.addItem(ob[0]);
        }
        res.close();
        stt.close();
        con.close();
        } catch(Exception exc){
        System.err.println(exc.getMessage());}
}
// <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kodenilai = new javax.swing.JTextField();
        totalnilai = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        nilaipraktek = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        nilaipts = new javax.swing.JTextField();
        nilaipas = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        nilaiuh = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        rata_nilai = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tnis = new javax.swing.JComboBox();
        tnip = new javax.swing.JComboBox();
        ta = new javax.swing.JLabel();
        tb = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        totalnilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalnilaiActionPerformed(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jButton3.setText("UBAH");

        jButton4.setText("HAPUS");

        jButton5.setText("KELUAR");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FORM NILAI");

        jLabel2.setText("KODE_NILAI");

        jLabel3.setText("NIS");

        jLabel4.setText("NIP");

        jLabel5.setText("NILAI UH");

        jLabel6.setText("NILAI PRAKTEK");

        jLabel7.setText("NILAI PTS");

        jLabel8.setText("NILAI PAS");

        jLabel9.setText("TOTAL NILAI");

        tnis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih NIS" }));
        tnis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tnisItemStateChanged(evt);
            }
        });

        tnip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih NIP" }));
        tnip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tnipItemStateChanged(evt);
            }
        });

        ta.setText("A");

        tb.setText("B");

        tc.setText("C");

        jLabel10.setText("RATA-RATA NILAI");

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(47, 47, 47))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3))
                                    .addGap(90, 90, 90)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(kodenilai)
                                .addComponent(tnis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tnip, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ta)
                                .addComponent(tb)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(tc)
                            .addGap(1, 1, 1))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nilaiuh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nilaipas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nilaipraktek, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rata_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nilaipts, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tambah)
                    .addComponent(simpan)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kodenilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(ta))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tc)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(88, 88, 88))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nilaipraktek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(nilaipts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nilaipas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nilaiuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rata_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambah)
                        .addGap(30, 30, 30)
                        .addComponent(simpan)
                        .addGap(32, 32, 32)
                        .addComponent(jButton3)
                        .addGap(48, 48, 48)
                        .addComponent(jButton4)
                        .addGap(44, 44, 44)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String SQL;
    //ref_nis untuk muncul data nama
public void ref_nis()
    {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try
    {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    SQL = "SELECT nama FROM siswa WHERE NIS = '"+tnis.getSelectedItem()+"'";
    ResultSet rs = stt.executeQuery(SQL);
    while(rs.next())
    {
    ta.setText(rs.getString(1));
    }
    }
    catch(Exception e)
    {
    System.out.print(e);
    }
}

public void tampil_nip(){
    String hubung="jdbc:mysql://localhost:3306/sekolah";
    try{
    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
    Connection con=DriverManager.getConnection(hubung,"root","");
    Statement stt=con.createStatement();
    String sql = "Select nip from guru order by nip asc";
    ResultSet res= stt.executeQuery(sql);
    while(res.next()){
    Object[] ob = new Object[1];
    ob[0] = res.getString(1);
    tnip.addItem(ob[0]);
    }
    res.close();
    stt.close();
    con.close();
    } catch(Exception exc){
    System.err.println(exc.getMessage());}
}
// <editor-fold defaultstate="collapsed" desc="Generated Code">
public void ref_nip()
    {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try
    {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    SQL = "SELECT nama_guru,nama_mapel FROM guru WHERE nip = '"+tnip.getSelectedItem()+"'";
    ResultSet rs = stt.executeQuery(SQL);
    while(rs.next())
    {
    tb.setText(rs.getString(1));
    tc.setText(rs.getString(2));
    }
    }
    catch(Exception e)
    {
    System.out.print(e);
    }
}

    private void totalnilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalnilaiActionPerformed
        // TODO add your handling code here:
        //TOTALNILAI
    }//GEN-LAST:event_totalnilaiActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        int num1 = Integer.parseInt(nilaiuh.getText());
        int num2 = Integer.parseInt(nilaipraktek.getText());
        int num3 = Integer.parseInt(nilaipts.getText());
        int num4 = Integer.parseInt(nilaipas.getText());
        int total = num1 + num2 + num3 + num4;
        int rata_rata = total / 4;
        totalnilai.setText(Integer.toString(total));
        rata_nilai.setText(Integer.toString(rata_rata));
    }//GEN-LAST:event_tambahActionPerformed

    private void tnisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tnisItemStateChanged
        // TODO add your handling code here:
        ref_nis();
    }//GEN-LAST:event_tnisItemStateChanged

    private void tnipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tnipItemStateChanged
        // TODO add your handling code here:
        ref_nip();
    }//GEN-LAST:event_tnipItemStateChanged

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "insert into siswa values('"+kodenilai.getText()+"','"+tnis.getSelectedItem()+"','"+tnip.getSelectedItem()+"','"+nilaiuh.getText()+"','"+nilaipraktek.getText()+"','"+nilaipts.getText()+"','"+nilaipas.getText()+"','"+totalnilai.getText()+"','"+rata_nilai.getText()+"')";
            stt.executeUpdate(SQL);
            data[0]=kodenilai.getText();
            data[1]=tnis.getSelectedItem().toString();
            data[2]=tnip.getSelectedItem().toString();
            data[3]=nilaiuh.getText();
            data[4]=nilaipraktek.getText();
            data[5]=nilaipts.getText();
            data[6]=nilaipas.getText();
            data[7]=totalnilai.getText();
            data[8]=rata_nilai.getText();
            //tblModel.insertRow(0, data);
            kodenilai.setText("");
            tnis.setSelectedItem("-=NIS=-");
            tnip.setSelectedItem("-=NIP=-");
            nilaiuh.setText("");
            nilaipraktek.setText("");
            nilaipts.setText("");
            nilaipas.setText("");
            totalnilai.setText("");
            rata_nilai.setText("");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_simpanActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kodenilai;
    private javax.swing.JTextField nilaipas;
    private javax.swing.JTextField nilaipraktek;
    private javax.swing.JTextField nilaipts;
    private javax.swing.JTextField nilaiuh;
    private javax.swing.JTextField rata_nilai;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel ta;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel tb;
    private javax.swing.JLabel tc;
    private javax.swing.JComboBox tnip;
    private javax.swing.JComboBox tnis;
    private javax.swing.JTextField totalnilai;
    // End of variables declaration//GEN-END:variables
}
